name: mkdocs-merge

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'poetry.lock'

permissions:
  contents: write

jobs:
  mkdocs-merge-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Use a local virtual environment in .venv directory
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - uses: actions/cache@v4
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install the project dependencies
        run: poetry install --no-root # No root skips installing the project itself. There is none.
      - name: Deploy to gh-pages branch
        run: poetry run mkdocs gh-deploy --force # -f mkdocs.yml